
.PHONY: default check compile clean style

default: compile

compile:
	$(MAKE) -C CompoundInterest
	$(MAKE) -C IntList

check:
	$(MAKE) -C CompoundInterest check
	$(MAKE) -C IntList check

style:
	$(MAKE) -C CompoundInterest style
	$(MAKE) -C IntList style

clean:
	$(MAKE) -C CompoundInterest clean
	$(MAKE) -C IntList clean

